wolips/core/plugins/org.objectstyle.wolips.componenteditor/java/org/objectstyle/wolips/componenteditor/part/HtmlWodTab.java
This append when opening a component editor if the previously used one was optimized for heretic people like me not using the WOD part and prefer inline bindings.
This is a temporary patch to keep the workspace usable. Before 4.4, this was supported but I do not know how to fix it properly.
=> Make sure the is enough space for a minimal WOD editor to prevent a NPE

wolips/core/plugins/org.objectstyle.wolips.bindings/java/org/objectstyle/wolips/bindings/api/ApiModel.java
A newly created API file and the blankContent-API fallback have the declaration
<code><?xml version = "1.0" encoding = "UTF-8" standalone = "yes"?></code>
but when saving the <i>standalone = "yes"</i> part will be removed.
=> output standalone="yes" when saving API file

wolips/core/plugins/org.objectstyle.wolips.bindings/java/org/objectstyle/wolips/bindings/preferences/BindingValidationPreferencePage.java, wolips/core/plugins/org.objectstyle.wolips.bindings/java/org/objectstyle/wolips/bindings/preferences/PreferenceConstants.java, wolips/core/plugins/org.objectstyle.wolips.bindings/java/org/objectstyle/wolips/bindings/preferences/PreferenceInitializer.java, wolips/core/plugins/org.objectstyle.wolips.bindings/java/org/objectstyle/wolips/bindings/utils/BindingReflectionUtils.java, wolips/core/plugins/org.objectstyle.wolips.bindings/java/org/objectstyle/wolips/bindings/wod/AbstractWodBinding.java, wolips/core/plugins/org.objectstyle.wolips.bindings/java/org/objectstyle/wolips/bindings/wod/AbstractWodElement.java, wolips/core/plugins/org.objectstyle.wolips.bindings/java/org/objectstyle/wolips/bindings/wod/WodBindingDeprecationProblem.java, wolips/core/plugins/org.objectstyle.wolips.bindings/java/org/objectstyle/wolips/bindings/wod/WodElementDeprecationProblem.java, wolips/core/plugins/org.objectstyle.wolips.tkhtmleditor/java/org/objectstyle/wolips/templateeditor/InlineWodTagInfo.java, wolips/core/plugins/org.objectstyle.wolips.tkhtmleditor/java/org/objectstyle/wolips/templateeditor/TemplateAssistProcessor.java, wolips/core/plugins/org.objectstyle.wolips.tkhtmleditor/java/tk/eclipse/plugin/htmleditor/assist/AssistInfo.java, wolips/core/plugins/org.objectstyle.wolips.tkhtmleditor/java/tk/eclipse/plugin/htmleditor/assist/HTMLAssistProcessor.java, wolips/core/plugins/org.objectstyle.wolips.tkhtmleditor/java/tk/eclipse/plugin/htmleditor/assist/HTMLDeprecatedCompletionProposal.java, wolips/core/plugins/org.objectstyle.wolips.tkhtmleditor/java/tk/eclipse/plugin/htmleditor/editors/HTMLConfiguration.java, wolips/core/plugins/org.objectstyle.wolips.wodclipse.core/java/org/objectstyle/wolips/wodclipse/core/completion/WodCompletionUtils.java, wolips/core/plugins/org.objectstyle.wolips.wodclipse.core/java/org/objectstyle/wolips/wodclipse/core/completion/WodDeprecatedCompletionProposal.java, wolips/core/plugins/org.objectstyle.wolips.wodclipse.core/java/org/objectstyle/wolips/wodclipse/core/validation/InlineWodProblem.java, wolips/core/plugins/org.objectstyle.wolips.wodclipse/java/org/objectstyle/wolips/wodclipse/editor/WodSourceViewerConfiguration.java
This patch adds validation checks for deprecated classes/methods/variables so that the popup menus with completion proposals in the HTML and Wod editor display bindings stroked through. Additionally warning/error markers are created for deprecated elements and bindings. This can be controlled by adding a setting to the WOLips validation preference pane.
=> Visualize deprecation status of bindings in editors

wolips/core/plugins/org.objectstyle.wolips.eomodeler.core/java/org/objectstyle/wolips/eomodeler/core/model/EOAttribute.java, wolips/core/plugins/org.objectstyle.wolips.eomodeler.core/templates/EntityMigration0.java
The class Migration defines two constants ALLOWS_NULL and NOT_NULL to make the creation of table columns more readable. This patch replaces the former true/false parameters with those constants.
=> use constants ALLOWS_NULL and NOT_NULL in migrations

wolips/core/plugins/org.objectstyle.wolips.pbserver/java/org/objectstyle/wolips/pbserver/PBServerPlugin.java, wolips/core/plugins/org.objectstyle.wolips.pbserver/java/org/objectstyle/wolips/pbserver/PBServerStartup.java, wolips/core/plugins/org.objectstyle.wolips.pbserver/plugin.xml, wolips/core/plugins/org.objectstyle.wolips.womodeler/java/org/objectstyle/wolips/womodeler/Activator.java, wolips/core/plugins/org.objectstyle.wolips.womodeler/java/org/objectstyle/wolips/womodeler/WOModelerStartup.java, wolips/core/plugins/org.objectstyle.wolips.womodeler/plugin.xml
In eclipse 4.5 there is a new deprecation warning in case of a plugin which has an extension of "org.eclipse.ui.startup" which is not configured properly. This fix will configure the affected wolips-plugins according to the documentation.
This warning is displayed because of a change in eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=50164
>The 'org.eclipse.ui.startup' extension from 'org.objectstyle.wolips.womodeler' does not provide a 'class' attribute.
>This usage is deprecated and a 'class' attribute should be provided.
>The release after Mars (4.5) will no longer support the deprecated usage!
> This extension point is used to register plug-ins that want to be activated on startup. The class given as the attribute on the startup element must implement the interface …
=> Eclipse 4.5 (Mars) compatibility: UI startup deprecation fix

wolips/core/plugins/org.objectstyle.wolips.templateengine/java/org/objectstyle/wolips/templateengine/ProjectTemplate.java
**Project- and Component-Templates are not working when there is a SPACE in the path to the eclipse installation.**
There is an old eclipse-bug which results in FileLocator.toFileURL returning an broken URL when there are spaces in the path.
The eclipse bug for this problem: https://bugs.eclipse.org/bugs/show_bug.cgi?id=145096
The problem is that eclipse is using the deprecated `file.toURL()` in FileBundleEntry.getFileURL().
This method is deprecated with the message:
> Deprecated. This method does not automatically escape characters that are illegal in URLs. It is recommended that new code convert an abstract pathname into a URL by first converting it into a URI, via the toURI method, and then converting the URI into a URL via the URI.toURL method.
The correct method to use in the …
=> bugfix for eclipse bug 145096 where filelocator returns broken url

wolips/core/plugins/org.objectstyle.wolips.eogenerator.core/templates/WonderEntity.java, wolips/core/plugins/org.objectstyle.wolips.eogenerator.core/templates/_WonderEntity.java
This makes some smaller improvements to the WonderEntity and _WonderEntity templates that are used by EOGenerator. All changes should have no impact on existing projects. The most notable changes are:
* use slf4j for logging instead of log4j
* static keys for attributes and relationships are only created in the defining class, before those were recreated in every subentity when using inheritance
* replaced one usage of EOFetchSpecification by ERXFetchSpecification
=> Improve Wonder entity templates

wolips/core/plugins/org.objectstyle.wolips.apieditor/java/org/objectstyle/wolips/apieditor/editor/ApiEditor.java, wolips/core/plugins/org.objectstyle.wolips.templateengine/java/org/objectstyle/wolips/templateengine/AbstractEngine.java, wolips/core/plugins/org.objectstyle.wolips.templateengine/java/org/objectstyle/wolips/templateengine/TemplateEngine.java, wolips/core/plugins/org.objectstyle.wolips.templateengine/java/org/objectstyle/wolips/templateengine/TemplateEnginePlugin.java, wolips/core/plugins/org.objectstyle.wolips.tkhtmleditor/java/org/objectstyle/wolips/templateeditor/TemplateOutlinePage.java
As every year eclipse did some breaking changes to their API.
This commits should migrate the WOLips-Plugin to Eclipse 4.6 compatibility without breaking the compatibility to eclipse versions before 4.6.
=> Eclipse 4 6 compatibility

wolips/core/plugins/org.objectstyle.wolips.tkhtmleditor/java/org/objectstyle/wolips/templateeditor/TemplateOutlinePage.java
After the migration to support eclipse 4.6 unfortunately the support to compile against eclipse 4.4 was dropped.
* Readded the missing casts (The new version uses generics and the old version requires casts).
Tested compilation against eclipse versions 4.4, 4.5 and 4.6
=> readded some casts to be able to compile against eclipse 4.4

wolips/core/plugins/org.objectstyle.wolips.baseforplugins/java/org/objectstyle/wolips/baseforplugins/util/FilesystemProject.java, wolips/core/plugins/org.objectstyle.wolips.wizards/java/org/objectstyle/wolips/wizards/NewComponentCreationPage.java
As every year eclipse did some breaking changes to their API.
This commits should migrate the WOLips-Plugin to Eclipse 4.7 compatibility without breaking the compatibility to eclipse versions before 4.7.
* Tested with Eclipse 4.7.M6
* added required implementation of a new IProject-Method. 
* The new method has no Override-Annotation for the purpose of backward-compatibility
* Changed Warning-Text-Generation in the "WOComponent Controller/View"-Wizard
* it used newly restricted Eclipse-API "BasicElementLabels"
* The new Warning-Text-Generation produces the same texts as the old method
=> Eclipse 4.7 compatibility

woproject-ant-tasks/src/resources/woapp_52/Contents/MacOS/appstart
This ports Lachlan Deck's addition to the woapp version of this file to the woapp_52 one. It'll enable correct handling of javaagent launch arguments via "---javaagent:fooBar.jar".
=> Handle java agent launch arguments

woenvironment/src/java/org/objectstyle/woenvironment/env/WOEnvironment.java, woenvironment/src/java/org/objectstyle/woenvironment/env/WOVariables.java, woproject-ant-tasks/pom.xml
While trying to release a new version of woproject-ant-tasks, I faced compilation failures on multiple classes. All of them caused by a `reference to WOEnvironment is ambiguous` error. E.g.:
```
[ERROR] .../org/objectstyle/woproject/ant/WOApplication.java:[556,21] reference to WOEnvironment is ambiguous
[ERROR]   both constructor WOEnvironment(java.util.Map<java.lang.Object,java.lang.Object>) in org.objectstyle.woenvironment.env.WOEnvironment 
and constructor WOEnvironment(java.util.Hashtable<java.lang.String,java.lang.Object>) in org.objectstyle.woenvironment.env.WOEnvironment match
```
Java is unable to choose between `Map<Object, Object>` and `Hashtable<String, Object>` when you pass a raw `Hashtable` as a parameter. Oh, the joy of Java Generics. It always confuses me. :)
I was digging …
=> Fix compilation failure on woproject-ant-tasks

default.properties, wolips/core/plugins/org.objectstyle.wolips.baseforplugins/META-INF/MANIFEST.MF, wolips/core/plugins/org.objectstyle.wolips.baseforplugins/java/org/objectstyle/wolips/baseforplugins/util/FilesystemProject.java, wolips/core/plugins/org.objectstyle.wolips.baseforplugins/java/org/objectstyle/wolips/baseforplugins/util/StringUtilities.java, wolips/core/plugins/org.objectstyle.wolips.baseforuiplugins/java/org/objectstyle/wolips/baseforuiplugins/utils/KeyComboBoxCellEditor.java, wolips/core/plugins/org.objectstyle.wolips.componenteditor/java/org/objectstyle/wolips/componenteditor/inspector/BindingsDragHandler.java, wolips/core/plugins/org.objectstyle.wolips.launching/java/org/objectstyle/wolips/launching/ui/AbstractWOArgumentsTab.java, wolips/core/plugins/org.objectstyle.wolips.mechanic/.classpath, wolips/core/plugins/org.objectstyle.wolips.mechanic/src/org/objectstyle/wolips/mechanic/ImportProjectTaskScanner.java, wolips/core/plugins/org.objectstyle.wolips.mechanic/src/org/objectstyle/wolips/mechanic/ImportProjectsTask.java, wolips/core/plugins/org.objectstyle.wolips.tkhtmleditor/java/tk/eclipse/plugin/htmleditor/editors/NonRuleBasedDamagerRepairer.java, wolips/entityModeler/.classpath, wolips/entityModeler/.settings/org.eclipse.jdt.core.prefs, wolips/entityModeler/META-INF/MANIFEST.MF, wolips/entityModeler/java/entitymodeler/ApplicationWorkbenchAdvisor.java, wolips/eomodeldoc/.classpath, wolips/veogen/.classpath
This seems to restore the EOModeler functionality  #146, but more tests are needed.
The build will only work with Java 11+, because some needed Eclipse classes have the corresponding class file version 55.
The changes to the workspace mechanic plugin are similar to PR 141.
=> Make WOLips build with Eclipse 2020-09 (4.17.0)

wolips/core/plugins/org.objectstyle.wolips.launching/java/org/objectstyle/wolips/launching/classpath/WORuntimeClasspathProvider.java
WOLips always includes test dependencies when running WOApplications inside Eclipse, which may be problematic if a project has conflicting dependencies with test and runtime scopes. This fix supports the `Exclude Test Code` option of launching configurations. When enabled, WOLips won't include test dependencies in the classpath anymore.
=> Support the Exclude Test Code option in WO launching configurations

wolips/core/plugins/org.objectstyle.wolips.womodeler/java/org/objectstyle/wolips/womodeler/OpenJavaFileRequestHandler.java, wolips/core/plugins/org.objectstyle.wolips.womodeler/java/org/objectstyle/wolips/womodeler/WOModelerStartup.java
Adds a request handler ```/openJavaFile``` to the WOLips server. The idea is to add link to line numbers in stack traces shown in WOExceptionPage, so the relevant file/location can be opened directly in Eclipse.
The URL structure is:
```http://localhost:9485/openJavaFile?pw={pw}&app={app}className={className}&lineNumber={lineNumber}```
Where
* ```pw``` WOLips server password as set in preferences
* ```app``` The application's name (which duplicates as the eclipse project name)
* ```className``` Fully qualified name of the Java class to open
* ```lineNumber``` Line number to navigate to when the file is opened
To complete the issue, WOExceptionPage/ERXException page must also be updated to link to the relevant URLs.
=> Added request handler to the WOLips server for opening java files #144

wolips/core/plugins/org.objectstyle.wolips.eomodeler.core/templates/EntityMigration0.java
This pull request introduces support for java.time migration generation in Entity Modeler. Despite java.time prototypes being supported for several years in Wonder, attempts to generate migrations for entities using these types have previously resulted in errors.
For instance, users might encounter the following error message:
With this update, the Entity Modeler can now successfully generate migrations for java.time types. The migration generation will adhere to the following rules:
```
| Prototype         | New Column Method  |
|-------------------|--------------------|
| javaDateTime      | newTimestampColumn |
| javaLocalDate     | newDateColumn      |
| javaLocalDateTime | newTimestampColumn |
| javaLocalTime     | newTimeColumn      |
```
The result can be seem in the image below:
=> Add support for generating migrations for java.time prototypes

wolips/core/plugins/org.objectstyle.wolips.builder/java/org/objectstyle/wolips/builder/internal/WOIncrementalBuilder.java, wolips/core/plugins/org.objectstyle.wolips.eomodeler.eclipse/java/org/objectstyle/wolips/eomodeler/eclipse/EclipseEOModelGroupFactory.java
Building WebObject projects in Eclipse 4.31 fails with an error:
`class org.eclipse.jdt.internal.core.JavaNature cannot be cast to class org.eclipse.jdt.core.IJavaProject (org.eclipse.jdt.internal.core.JavaNature and org.eclipse.jdt.core.IJavaProject are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @...)`
This PR resolves this error by using another way to get the IJavaProject.
It also replaces the deprecated SubProgressMonitor with a SubMonitor.
=> Support for Eclipse 4.31 (2024-03)

wolips/core/plugins/org.objectstyle.wolips.bindings/java/org/objectstyle/wolips/bindings/utils/BindingReflectionUtils.java
Quick hack to support java record components in the component editor. No idea if this is the "right way" design wise, but after using it for a day it's at least definitely an improvement over the current situation.
=> Support java records in component editor

wolips.targetplatform/wolips.targetplatform.target
Some notes:
- I have commented the "org.eclipse.linuxtools" entries, because I didn't find them anymore.
- I have commented SpotBugs, because in Eclipse PDE I can find the new version 4.9.3, but a `mvn clean package` still fails.
=> Updated wolips.targetplatform.target to Eclipse 2025-03

wolips/plugins/org.objectstyle.wolips.componenteditor/java/org/objectstyle/wolips/componenteditor/part/HtmlWodTab.java
Opening a regular HTML file in the template editor often failed, since the template editor tried to do some editor layout cleanup/alignment that expected a .wod editor to be present. This just disables that layout cleanup if no .wod is present (which is redundant anyway since there's nothing to align).
=> Prevent an error from occurring when opening an HTML-file in the template editor
